import { ApplicationConfig } from '@angular/core';
import { routes } from './app.routes';
import { provideRouter } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import {
  HTTP_INTERCEPTORS,
  provideHttpClient,
  withInterceptorsFromDi,
} from '@angular/common/http';
import { AuthInterceptor } from './interceptors/auth.interceptor';
import { MessageService, ConfirmationService } from 'primeng/api';
import { providePrimeNG } from 'primeng/config';
import Aura from '@primeng/themes/aura';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideAnimationsAsync(),
    provideHttpClient(withInterceptorsFromDi()),
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true },
    MessageService,
    ConfirmationService,
    providePrimeNG({
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: false,
        },
      },
      translation: {
        accept: 'Sí',
        addRule: 'Agregar regla',
        after: 'Después de',
        am: 'AM',
        apply: 'Aplicar',
        before: 'Antes de',
        cancel: 'Cancelar',
        choose: 'Elegir',
        chooseDate: 'Elige fecha',
        chooseMonth: 'Elige el mes',
        chooseYear: 'Elige Año',
        clear: 'Limpiar',
        contains: 'Contenga',
        dateAfter: 'Fecha después de',
        dateBefore: 'Fecha antes de',
        dateFormat: 'dd/mm/yy',
        dateIs: 'Fecha igual a',
        dateIsNot: 'Fecha diferente a',
        dayNames: [
          'Domingo',
          'Lunes',
          'Martes',
          'Miércoles',
          'Jueves',
          'Viernes',
          'Sábado',
        ],
        dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
        emptyFilterMessage: 'Sin opciones disponibles',
        emptyMessage: 'No se han encontrado resultados',
        emptySearchMessage: 'Sin opciones disponibles',
        emptySelectionMessage: 'Ningún artículo seleccionado',
        endsWith: 'Termine con',
        equals: 'Igual a',
        fileChosenMessage: '{0} archivos',
        fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
        firstDayOfWeek: 1,
        gt: 'Mayor que',
        gte: 'Mayor o igual a',
        is: 'Es',
        isNot: 'No es',
        lt: 'Menor que',
        lte: 'Menor o igual a',
        matchAll: 'Coincidir todo',
        matchAny: 'Coincidir con cualquiera',
        medium: 'Medio',
        monthNames: [
          'Enero',
          'Febrero',
          'Marzo',
          'Abril',
          'Mayo',
          'Junio',
          'Julio',
          'Agosto',
          'Septiembre',
          'Octubre',
          'Noviembre',
          'Diciembre',
        ],
        monthNamesShort: [
          'Ene',
          'Feb',
          'Mar',
          'Abr',
          'May',
          'Jun',
          'Jul',
          'Ago',
          'Sep',
          'Oct',
          'Nov',
          'Dic',
        ],
        nextDecade: 'Próxima década',
        nextHour: 'Próxima hora',
        nextMinute: 'Siguiente minuto',
        nextMonth: 'Próximo mes',
        nextSecond: 'Siguiente segundo',
        nextYear: 'El próximo año',
        noFileChosenMessage: 'No se ha elegido ningún archivo',
        noFilter: 'Sin filtro',
        notContains: 'No contenga',
        notEquals: 'Diferente a',
        passwordPrompt: 'Ingrese una contraseña',
        pending: 'Pendiente',
        pm: 'PM',
        prevDecade: 'Década anterior',
        prevHour: 'Hora anterior',
        prevMinute: 'Minuto anterior',
        prevMonth: 'Mes anterior',
        prevSecond: 'Anterior Segundo',
        prevYear: 'Año anterior',
        reject: 'No',
        removeRule: 'Eliminar regla',
        searchMessage: '{0} resultados están disponibles',
        selectionMessage: '{0} elementos seleccionados',
        startsWith: 'Comience con',
        strong: 'Fuerte',
        today: 'Hoy',
        upload: 'Subir',
        weak: 'Débil',
        weekHeader: 'Sem',
        aria: {
          browseFiles: 'Buscar archivos',
          cancelEdit: 'Cancelar editado',
          close: 'Cerrar',
          collapseRow: 'Reducir Fila',
          editRow: 'Editar fila',
          expandRow: 'Expandir Fila',
          falseLabel: 'Falso',
          filterConstraint: 'Restricción de filtro',
          filterOperator: 'Operador de filtro',
          firstPageLabel: 'Primera Página',
          gridView: 'Vista de cuadrícula',
          hideFilterMenu: 'Ocultar menú del filtro',
          jumpToPageDropdownLabel: 'Ir al menú desplegable de página',
          jumpToPageInputLabel: 'Ir a la entrada de página',
          lastPageLabel: 'Última Página',
          listLabel: 'Lista de opciones',
          listView: 'Vista de lista',
          maximizeLabel: 'Maximizar',
          moveAllToSource: 'Mover todo al origen',
          moveAllToTarget: 'Mover todo al objetivo',
          moveBottom: 'Desplazarse hacia abajo',
          moveDown: 'Bajar',
          moveToSource: 'Mover al origen',
          moveToTarget: 'Mover al objetivo',
          moveTop: 'Mover arriba',
          moveUp: 'Subir',
          navigation: 'Navegación',
          next: 'Siguiente',
          nextPageLabel: 'Siguiente Página',
          nullLabel: 'No seleccionado',
          pageLabel: 'Página {page}',
          prevPageLabel: 'Página Anterior',
          previous: 'Anterior',
          previousPageLabel: 'Página Anterior',
          removeLabel: 'Eliminar',
          rotateLeft: 'Girar a la izquierda',
          rotateRight: 'Girar a la derecha',
          rowsPerPageLabel: 'Filas por página',
          saveEdit: 'Guardar editado',
          scrollTop: 'Desplazarse hacia arriba',
          selectAll: 'Seleccionar todos',
          selectColor: 'Seleccione un color',
          selectRow: 'Seleccionar fila',
          showFilterMenu: 'Mostrar menú del filtro',
          slide: 'Deslizar',
          slideNumber: '{slideNumber}',
          star: '1 estrella',
          stars: '{star} estrellas',
          trueLabel: 'Verdadero',
          unselectAll: 'Deseleccionar todos',
          unselectRow: 'Desmarcar fila',
          zoomImage: 'Ampliar imagen',
          zoomIn: 'Ampliar',
          zoomOut: 'Reducir',
        },
      },
    }),
  ],
};
