DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'aplicacion') THEN
    CREATE USER aplicacion WITH PASSWORD 'aplicacion123';
  END IF;
END
$$;
GRANT USAGE ON SCHEMA public TO aplicacion;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO aplicacion;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO aplicacion;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO aplicacion;
ALTER USER aplicacion WITH SUPERUSER;
